web/router.ex
defmodule Prueba.Router do
  use Prueba.Web, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", Prueba do
    pipe_through :browser # Use the default browser stack

    get "/", PageController, :index
    
    get "/quienesomos", InfoController, :index
    get "/quienesomos/vision", InfoController, :vision
    get "/quienesomos/mision", InfoController, :mision
    get "/quienesomos/valores", InfoController, :valores
    get "/quienesomos/historia", InfoController, :historia
    resources "/investigadores", InvestigadorController
    resources "/alumnos", AlumnoController
    resources "/vinculaciones", VinculacionController
    resources "/publicaciones", PublicacionController
  end

  # Other scopes may use custom stacks.
  # scope "/api", Prueba do
  #   pipe_through :api
  # end
end

web/views/layout_view.ex
defmodule Prueba.LayoutView do
  use Prueba.Web, :view
end

web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="stylesheet" href="<%= static_path(@conn, "/css/app.css") %>" />

    <link rel="stylesheet" href="<%= static_path(@conn, "/css/estilo3.css") %>" />
    <title>  GIIE UPIICSA</title>

    <!-- Bootstrap CSS -->
   <!-- <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/css/bootstrap.min.css" integrity="sha384-/Y6pD6FV/Vv2HJnA6t+vslU6fwYXjCFtcEpHbNJ0lyAFsXTsjBbfaDjzALeQsN6M" crossorigin="anonymous">-->
    
  </head>

  <body>

    <div class="row preview-html" ng-show="screen == 'preview'" ng-hide="loading">
      <div class="col-md-12"><div id="cssmenu">
          <ul>

            <li class="has-sub"><a href="#"><span><i class="fa fa-fw fa-bars"></i> Nosotros</span></a>
                <ul>
                   <li><a href=" <%= info_path(@conn, :historia) %> "><span>Historia</span></a></li>
                </ul>
             </li>

             <li class="has-sub"><a href="#"><span><i class="fa fa-fw fa-bars"></i> Investigadores</span></a>
                <ul>
                   <li class="has-sub"><a href="#"><span>Academicos</span></a>
                      <ul>
                         <li><a href="#"><span>Marina Vicario</span></a></li>
                      </ul>
                   </li>
                   <li class="has-sub"><a href="#"><span>Academicos</span></a>
                      <ul>
                         <li><a href="<%= alumno_path(@conn, :show,1) %>"><span>Armando Lopez Rojas</span></a></li>
                         <li><a href="<%= alumno_path(@conn, :show,2) %>"><span>Ana Ivette Sierra Mena</span></a></li>
                         <li><a href="<%= alumno_path(@conn, :show,3) %>"><span>Diana Laura Barrios Solar</span></a></li>
                         <li><a href="<%= alumno_path(@conn, :show,4) %>"><span>Mario Arturo Romero Ochoa</span></a></li>

                      </ul>
                   </li>
                </ul>
             </li>
             <li class="has-sub"><a href="#"><span><i class="fa fa-fw fa-bars"></i> Vinculacion</span></a>
                <ul>
                    <li ><a href="#"><span>Red Late</span></a></li>
                    <li ><a href="#"><span>ILCE</span></a></li>
                    <li ><a href="#"><span>AEM</span></a></li>
                    <li ><a href="#"><span>SOMECE</span></a></li>
                    <li ><a href="#"><span>UNAM</span></a></li>
                    <li ><a href="#"><span>NÉTICA</span></a></li>
                    <li ><a href="#"><span>Caldera Studio</span></a></li>
                    <li ><a href="#"><span>Hacedores</span></a></li>
                    <li ><a href="#"><span>Instituto Galileo</span></a></li>
                    <li ><a href="#"><span>CIC</span></a></li>
                    <li ><a href="#"><span>ESCOM</span></a></li>
                    <li ><a href="#"><span>UPIITA</span></a></li>
                    <li ><a href="#"><span>CUDI</span></a></li>
                </ul>
             </li>

             <li class="has-sub"><a href="#"><span><i class="fa fa-fw fa-bars"></i>Desarrollo</span></a>
                <ul>
                    <li ><a href="#"><span>MathBot</span></a></li>
                    <li ><a href="#"><span>NAMIT</span></a></li>
                    <li ><a href="#"><span>Oca Algebraica</span></a></li>
                </ul>
             </li>

             <li class="has-sub"><a href="#"><span><i class="fa fa-fw fa-bars"></i>Productos</span></a>
                <ul>
                    <li ><a href="#"><span>MathBot</span></a></li>
                    <li ><a href="#"><span>NAMIT</span></a></li>
                    <li ><a href="#"><span>Oca Algebraica</span></a></li>
                </ul>
             </li>


             <li class="has-sub"><a href="#"><span><i class="fa fa-fw fa-bars"></i>Publicaciones</span></a>
                <ul>
                    <li ><a href="<%= publicacion_path(@conn, :index) %>"><span>Articulos</span></a></li>
                    <li ><a href="#"><span>Libros</span></a></li>
                </ul>
             </li>



             <li><a href="#"><span><i class="fa fa-fw fa-phone"></i>Contacto</span></a></li>
          </ul>

      </div>
    </div>
    
    <!-- Fin del Menú -->
    <br><br><br>
    <div id="cabecera">
        <h2 align="center">
          GIIE UPIICSA
        </h2>
      </div>
    
    <main role="main">
        <%= render @view_module, @view_template, assigns %>
    </main>
     <!-- /container -->

    <script src="<%= static_path(@conn, "/js/app.js") %>"></script>

    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.11.0/umd/popper.min.js" integrity="sha384-b/U6ypiBEHpOf/4+1nzFpr53nxSS+GLCkfwBdFNTxtclqqenISfwAzpKaMNFNmj4" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/js/bootstrap.min.js" integrity="sha384-h0AbiXch4ZDo7tp9hKZ4TsHbi047NrKGLO3SEJAg45jXxnGIfYzk4Si90RDIqNm1" crossorigin="anonymous"></script>
  </body>
</html>